# Generated by Django 2.2.20 on 2021-07-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
