# Generated by Django 2.2.20 on 2021-07-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='breakinh',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
