# Generated by Django 2.2.20 on 2021-07-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210704_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='breakinh',
            new_name='breaking',
        ),
        migrations.AddField(
            model_name='customtext',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
    ]
